# Generated by Django 4.0.3 on 2022-08-14 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(default='00-00-00-00', max_length=255)),
                ('cel', models.CharField(default='00-00-00-00', max_length=255)),
                ('moto', models.CharField(blank=True, max_length=255, null=True)),
                ('year_founded', models.CharField(blank=True, max_length=4, null=True)),
                ('mgt_quote', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ad_copy', models.TextField(blank=True, null=True)),
                ('resumption', models.CharField(blank=True, default='', max_length=180, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('pedagogy', models.TextField(blank=True, null=True)),
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('diplomas', models.CharField(blank=True, max_length=255, null=True)),
                ('courses', models.CharField(blank=True, max_length=255, null=True)),
                ('time_range', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.IntegerField(blank=True, default='0', null=True)),
                ('students', models.IntegerField(blank=True, default='0', null=True)),
                ('curriculums', models.IntegerField(blank=True, default='0', null=True)),
                ('success_rate', models.IntegerField(blank=True, default='0', null=True)),
                ('classes', models.IntegerField(blank=True, default='0', null=True)),
                ('labs', models.IntegerField(blank=True, default='0', null=True)),
                ('libs', models.IntegerField(blank=True, default='0', null=True)),
                ('canteens', models.IntegerField(blank=True, default='0', null=True)),
                ('faculties', models.IntegerField(blank=True, default='0', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='schools/thumbnails')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='schools/banners')),
                ('crest', models.ImageField(blank=True, null=True, upload_to='schools/crests')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('edu_levels', models.ManyToManyField(blank=True, to='schools.edulevel')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tier', models.CharField(choices=[('free', 'Gratuit'), ('basic', 'Basique'), ('pro', 'Professionel')], default='free', max_length=50, null=True)),
                ('duration', models.CharField(choices=[('undefined', 'Indéfini'), ('month', 'Mois'), ('trimester', 'Trimestre'), ('semester', 'Semestre'), ('year', 'Année')], default='undefined', max_length=50, null=True)),
                ('price', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default='0')),
                ('fullname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('subjects', models.CharField(max_length=255)),
                ('qualifications', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/teachers')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(default='', max_length=255)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='year', max_length=4)),
                ('pass_rate', models.IntegerField(default='0')),
                ('fail_rate', models.IntegerField(default='0')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.subscription'),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/reports')),
                ('title', models.CharField(default='News Title', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, default='News')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/photos')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/libraries')),
                ('label', models.CharField(default='image label', max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('maxseats', models.IntegerField(default='0')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/laboratories')),
                ('label', models.CharField(default='image label', max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('maxseats', models.IntegerField(default='0')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/classrooms')),
                ('label', models.CharField(default='image label', max_length=255)),
                ('fee', models.IntegerField(default='0')),
                ('vacant_seats', models.IntegerField(default='0')),
                ('maxseats', models.IntegerField(default='0')),
                ('info', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/canteens')),
                ('label', models.CharField(default='image label', max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('maxseats', models.IntegerField(default='0')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(default='avantage', max_length=255)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
