# Generated by Django 4.0.3 on 2022-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('base', '0004_alter_school_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='school',
            name='edu_levels',
        ),
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='schools',
            field=models.ManyToManyField(to='schools.school'),
        ),
        migrations.DeleteModel(
            name='EduLevel',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
